[project]
name = "karabiner-config"
version = "0.1.0"
description = "Mutate Karabiner config Default profile"
readme = "README.md"
requires-python = ">=3.14,<3.15"
dependencies = ["pyyaml>=6.0.3,<6.1"]

[tool.ruff]
indent-width = 2

[tool.ruff.format]
quote-style = "single"
